package com.foodpartner.app.network

object OrderStatus {
    const val ORDER_PLACED = "ORDER_PLACED"
    const val ACCEPTED_BY_RESTAURANT = "ACCEPTED_BY_RESTAURANT"
    const val REJECTED_BY_RESTAURANT = "REJECTED_BY_RESTAURANT"
    const val PREPARING = "PREPARING"
    const val READY_FOR_PICKUP = "READY_FOR_PICKUP"

    const val DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED"
    const val DELIVERY_BOY_ARRIVED = "DELIVERY_BOY_ARRIVED"
    const val PICKED_UP = "PICKED_UP"

    const val ARRIVED_AT_CUSTOMER = "ARRIVED_AT_CUSTOMER"
    const val DELIVERED = "DELIVERED"

    const val CANCELLED_BY_CUSTOMER = "CANCELLED_BY_CUSTOMER"
    const val CANCELLED_BY_RESTAURANT = "CANCELLED_BY_RESTAURANT"
    const val DELIVERY_CANCELLED = "DELIVERY_CANCELLED"
}
